<?php
	defined('BASEPATH') OR exit('No direct script access allowed');
	$route['default_controller'] = 'login';
	$route['entrar'] = 'login/entrar';
	$route['sair'] = 'login/sair';
	$route['instituicoes'] = 'instituicao';
	$route['instituicao/cadastrar'] = 'instituicao/Cadastro_instituicao';
	$route['instituicao/editar/(:any)'] = 'instituicao/editar_instituicao/$1';
	$route['instituicao/editar/salvar/(:any)'] = 'instituicao/editar_salvar_instituicao/$1';
	$route['instituicao/cadastrar/salvar'] = 'instituicao/salvar_instituicao';
	$route['instituicao/deletar/(:any)'] = 'instituicao/deletar_instituicao/$1';
	$route['usuarios/cadastrar'] = 'usuarios/Cadastrar_usuario';
	$route['usuarios/deletar/(:any)'] = 'usuarios/deletar_atleta/$1';
	$route['usuarios/cadastrar/salvar'] = 'usuarios/salvar_usuario';
	$route['painel'] = 'painel';
	$route['painel/(:num)'] = 'painel';
	$route['filtro/pesquisa'] = 'painel/filtro';
	$route['filtro/pesquisa/relatorio'] = 'painel/filtro_relatorios';
	$route['filtro/pesquisa/relatorio/idade'] = 'painel/filtro_relatorio_idade';
	$route['atleta/cadastro'] = 'cadastro';
	$route['atleta/cadastro/salvar'] = 'cadastro/salvar_atleta';
	$route['atleta/deletar/(:any)'] ='cadastro/deletar_atleta/$1';
	$route['atleta/editar/(:any)'] ='cadastro/editar_atleta/$1';
	$route['atleta/editar/salvar/(:any)'] ='cadastro/editar_salvar_atleta/$1';
	$route['painel/relatorios'] = 'painel/Relatorios';
	$route['404_override'] = '';
	$route['translate_uri_dashes'] = FALSE;
